name = "timeoff-manager"
main = "src/worker.js"
compatibility_date = "2025-06-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "timeoff-manager-db"
database_id = "95ef3d44-4b8f-4802-97bd-8e50861e5f49"

[vars]
NODE_ENV = "production"

# Custom domain configuration
[[routes]]
pattern = "sapphireapp.site/*"
custom_domain = true

[[routes]]
pattern = "www.sapphireapp.site/*"
custom_domain = true

[env.production]
name = "timeoff-manager-prod"

[env.staging]
name = "timeoff-manager-staging"

[[assets]]
binding = "ASSETS"
directory = "./dist"