name = "timeoff-manager"
main = "src/worker.js"
compatibility_date = "2025-06-25"
compatibility_flags = ["nodejs_compat"]

# Wrangler v4 configuration
[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "timeoff-manager-db"
database_id = "95ef3d44-4b8f-4802-97bd-8e50861e5f49"

# Default environment variables
[vars]
NODE_ENV = "production"
APP_URL = "https://sapphireapp.site"
FROM_EMAIL = "noreply@sapphireapp.site"

# Production environment configuration
[env.production]
name = "timeoff-manager-prod"
routes = [
  { pattern = "sapphireapp.site/*", zone_name = "sapphireapp.site" },
  { pattern = "timeoff-manager.lamado.workers.dev/*" }
]

[env.production.vars]
NODE_ENV = "production"
APP_URL = "https://sapphireapp.site"
FROM_EMAIL = "noreply@sapphireapp.site"

# Development environment configuration
[env.development]
name = "timeoff-manager-dev"

[env.development.vars]
NODE_ENV = "development"
APP_URL = "https://timeoff-manager-dev.lamado.workers.dev"
FROM_EMAIL = "noreply@timeoff-manager-dev.lamado.workers.dev"

# Static assets configuration
[assets]
directory = "./dist"