name = "timeoff-manager"
main = "src/worker.js"
compatibility_date = "2025-06-25"

[[d1_databases]]
binding = "DB"
database_name = "timeoff-manager-db"
database_id = "your-database-id-will-be-generated"

[vars]
NODE_ENV = "production"

[env.production]
name = "timeoff-manager-prod"

[env.staging]
name = "timeoff-manager-staging"